name: Build & maybe upload PyPI package

on:
  push:
    branches:
    tags: ["*"]
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Always build & lint package.
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hynek/build-and-inspect-python-package@v1

  # Upload to real PyPI on GitHub Releases.
  release-pypi:
    name: Publish to PyPI
    environment: release-pypi
    if: github.repository_owner == 'python' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package

    permissions:
      id-token: write

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
